name: CI

on:
  push:
  pull_request:

jobs:
  static-analysis:
    strategy:
      matrix:
        os: ["ubuntu-latest"]
        python-version: ["3.11"]
    runs-on: ${{ matrix.os }}
    steps:
      - name: "checkout"
        uses: actions/checkout@v4

      - name: "install openmpi lib"
        run: sudo apt install -y libopenmpi-dev

      - name: "Setup Python 3.11"
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Load cached venv
        id: cached-poetry-deps
        uses: actions/cache@v4
        with:
          path: ./.venv
          key: venv-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}

      - name: Install mpi4py
        run: |
            sudo apt-get update
            sudo apt-get install libopenmpi-dev

      - name: Install library
        run: poetry sync

      - name: Check format, lint and type
        run: make ci
      # ingore tests until they are fixed
      #- name: Run test
      #  run: make test
